# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: build/
      - id: check-json
        exclude: build/
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/pinterest/ktlint
    rev: '1.3.1' # This is a recent ktlint version. Adjust if needed for your specific Kotlin setup.
    hooks:
      - id: ktlint
        args: [ "--android", "--experimental", "!**/generated/**", "!build/**" ] # Apply Android styling, experimental rules, and exclude generated/build files.
        # ktlint will use .editorconfig if present.
